services:
  - type: web
    name: red-studio
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python seed_file_db.py
    startCommand: gunicorn --workers 2 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: redstudio2026secretkey
      - key: PYTHON_VERSION
        value: 3.10.0
